[package]
name = "wayland-db"
version = "0.1.0"
edition = "2024"

[dependencies]
error_reporter = "1.0.0"
thiserror = "2.0.17"
quick-xml = "0.38.4"
rusqlite = "0.38.0"
indexmap = "2.12.1"
linearize = { version = "0.1.5", features = ["derive"] }
walkdir = "2.5.0"
regex = "1.12.2"
